name: Supabase Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Configure Supabase CLI and Deploy
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        npm install supabase-cli
        ./node_modules/.bin/supabase-cli login --url $SUPABASE_URL --key $SUPABASE_KEY
        ./node_modules/.bin/supabase-cli deploy

        # Configure Supabase CLI with your credentials
        supabase login --url $SUPABASE_URL --key $SUPABASE_KEY

        # Deploy your project to Supabase
        supabase deploy 
